
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/django_todo_list
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
jwt:
  access:
    key: heruighurighviey84y57yuvhrjhvrhtvrhtvhjr8u4v8njvertvn8ut8veu834uvndjkwe
    expiration-time: 7200000000
  refresh:
    key: evjrkhertvuheruth84y574y587yvbrhvjrtvhrjthv3u4895vuntervnjtkejrht89545y
    expiration-time: 604800000
server:
  port: 8081
